# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: home
description: "Homepage of Anna Potapenko."
keywords: "Anna Potapenko, NLP, Moscow, topic modeling, word embeddings, HSE, MSU"
url:
# baseurl: "/apotapenko.com"
baseurl: ""

google_analytics: UA-103954038-1
repo: http://github.com/anyap/apotapenko.com
disqus_shortname: "nandothemes"
disqus_site_shortname: "nandothemes"

# Author settings
author:
  name      : Anna Potapenko
  job       : AI researcher in language and biology
  bio       : "You can contact me at apotapenko[at]google.com."
  thumb     : /images/author.jpg
  email     : apotapenko@google.com
  url       : http://apotapenko.com
  #github    : http://github.com/nandomoreirame
  #twitter   : http://twitter.com/nandomoreirame
  #facebook  : http://facebook.com/anna.a.potapenko
  #linkedin  : http://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: bio
    title: Bio
  - slug: research
    title: Research
  - slug: teaching
    title: Teaching
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  #- slug: blog
  #  title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
